name: 'CIDIFF'
description: "Compare PR build size against main's build size."
author: 'carcinocron'
inputs:
  bootstrap:
    description: 'cli command for installing dependencies ex npm install'
    required: true
    default: 'npm install'
  build_command:
    description: 'cli command for building repository ex npm run build'
    required: true
    default: 'npm run build'
  dist_path:
    description: 'output path for the build package'
    required: true
    default: 'dist'
  main_branch:
    description: 'if not a PR, the branch to compare to'
    required: true
    default: 'main'
  cidiff_account:
    description: 'The ID of your CIDIFF account'
    required: true
  cidiff_api_key:
    description: 'A valid API Key for your CIDIFF account'
    required: true
  token:
    description: 'A valid API Key for your Github account with access to this repository'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
outputs:
  size: # output will be available to future steps
    description: 'CIDIFF'
branding:
  icon: 'hard-drive'
  color: 'blue'
