# save this file as .github/workflows/build-size.yml
name: Build Size
on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
jobs:
  Build-Size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '10.0.0'
      - uses: carcinocron/JSBundleSize@main
        with:
          bootstrap: yarn install
          build_command: yarn run build
          dist_path: dist
          token: ${{ secrets.GITHUB_TOKEN }}
          main_branch: main
